#############################################
# Stalwart Mail Server Configuration File   
#############################################

[macros]
host = "__HOST__"
default_domain = "__DOMAIN__"
base_path = "__BASE_PATH__"
default_directory = "__DIRECTORY__"
default_store = "__STORE__"

[include]
files = [ "%{BASE_PATH}%/etc/common/server.toml",
          "%{BASE_PATH}%/etc/common/tls.toml",
          "%{BASE_PATH}%/etc/common/store.toml",
          "%{BASE_PATH}%/etc/common/tracing.toml",
          "%{BASE_PATH}%/etc/common/sieve.toml",
          "%{BASE_PATH}%/etc/directory/imap.toml",
          "%{BASE_PATH}%/etc/directory/internal.toml",
          "%{BASE_PATH}%/etc/directory/ldap.toml",
          "%{BASE_PATH}%/etc/directory/lmtp.toml",
          "%{BASE_PATH}%/etc/directory/memory.toml",
          "%{BASE_PATH}%/etc/directory/sql.toml",
          "%{BASE_PATH}%/etc/store/elasticsearch.toml",
          "%{BASE_PATH}%/etc/store/fs.toml",
          "%{BASE_PATH}%/etc/store/foundationdb.toml",
          "%{BASE_PATH}%/etc/store/mysql.toml",
          "%{BASE_PATH}%/etc/store/postgresql.toml",
          "%{BASE_PATH}%/etc/store/redis.toml",
          "%{BASE_PATH}%/etc/store/rocksdb.toml",
          "%{BASE_PATH}%/etc/store/s3.toml",
          "%{BASE_PATH}%/etc/store/sqlite.toml",
          "%{BASE_PATH}%/etc/imap/listener.toml",
          "%{BASE_PATH}%/etc/imap/settings.toml",
          "%{BASE_PATH}%/etc/jmap/auth.toml",
          "%{BASE_PATH}%/etc/jmap/listener.toml",
          "%{BASE_PATH}%/etc/jmap/oauth.toml",
          "%{BASE_PATH}%/etc/jmap/protocol.toml",
          "%{BASE_PATH}%/etc/jmap/push.toml",
          "%{BASE_PATH}%/etc/jmap/ratelimit.toml",
          "%{BASE_PATH}%/etc/jmap/websockets.toml",
          "%{BASE_PATH}%/etc/smtp/auth.toml",
          "%{BASE_PATH}%/etc/smtp/listener.toml",
          "%{BASE_PATH}%/etc/smtp/milter.toml",
          "%{BASE_PATH}%/etc/smtp/queue.toml",
          "%{BASE_PATH}%/etc/smtp/remote.toml",
          "%{BASE_PATH}%/etc/smtp/report.toml",
          "%{BASE_PATH}%/etc/smtp/resolver.toml",
          "%{BASE_PATH}%/etc/smtp/session.toml",
          "%{BASE_PATH}%/etc/smtp/signature.toml",
          "%{BASE_PATH}%/etc/smtp/spamfilter.toml" ]
