[package]
name = "trc"
version = "0.9.2"
edition = "2021"
resolver = "2"

[dependencies]
event_macro = { path = "./event-macro" }
mail-auth = { version = "0.4" }
mail-parser = { version = "0.9", features = ["full_encoding", "ludicrous_mode"] } 
base64 = "0.22.1"
serde = "1.0"
serde_json = "1.0.120"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls-webpki-roots", "http2"]}
bincode = "1.3.3"
rtrb = "0.3.1"
parking_lot = "0.12.3"
tokio = { version = "1.23", features = ["net", "macros"] }
ahash = "0.8.11"

[features]
test_mode = []

[dev-dependencies]
