[package]
name = "jmap"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
store = { path = "../store" }
jmap_proto = { path = "../jmap-proto" }
utils = { path =  "../utils" }
smtp = { path =  "../smtp" }
smtp-proto = { git = "https://github.com/stalwartlabs/smtp-proto" }
mail-parser = { git = "https://github.com/stalwartlabs/mail-parser", features = ["full_encoding", "serde_support", "ludicrous_mode"] } 
mail-builder = { git = "https://github.com/stalwartlabs/mail-builder", features = ["ludicrous_mode"] }
mail-send = { git = "https://github.com/stalwartlabs/mail-send" } 
sieve-rs = { git = "https://github.com/stalwartlabs/sieve" }
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0"
hyper = { version = "1.0.0-rc.3", features = ["server", "http1", "http2"] }
http-body-util = "0.1.0-rc.2"
form_urlencoded = "1.1.0"
tracing = "0.1"
tokio = { version = "1.23", features = ["rt"] }
aes-gcm = "0.10.1"
aes-gcm-siv = "0.11.1"
bincode = "1.3.3"
form-data = { version = "0.4.2", features = ["sync"], default-features = false }
mime = "0.3.17"
sqlx = { version = "0.7.0-alpha.3", features = [ "runtime-tokio-rustls", "postgres", "mysql", "sqlite" ] }
futures-util = "0.3.28"
async-stream = "0.3.5"
base64 = "0.21"
p256 = { version = "0.13", features = ["ecdh"] }
hkdf = "0.12.3"
sha2 = "0.10.1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"]}
tokio-tungstenite = "0.19.0"
tungstenite = "0.19.0"
chrono = "0.4"

[dev-dependencies]
ece = "2.2"

[features]
test_mode = []
