[package]
name = "utils"
version = "0.3.5"
edition = "2021"
resolver = "2"

[dependencies]
rustls = "0.21.0"
rustls-pemfile = "1.0"
tokio = { version = "1.23", features = ["net", "macros"] }
tokio-rustls = { version = "0.24.0"}
serde = { version = "1.0", features = ["derive"]}
tracing = "0.1"
mail-auth = { git = "https://github.com/stalwartlabs/mail-auth" }
smtp-proto = { git = "https://github.com/stalwartlabs/smtp-proto" }
mail-send = { git = "https://github.com/stalwartlabs/mail-send", default-features = false, features = ["cram-md5", "skip-ehlo"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
tracing-opentelemetry = "0.18.0"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"] }
opentelemetry-otlp = { version = "0.11.0", features = ["http-proto", "reqwest-client"] }
opentelemetry-semantic-conventions = { version = "0.10.0" }
dashmap = "5.4"
ahash = { version = "0.8" }

[target.'cfg(unix)'.dependencies]
privdrop = "0.5.3"

[features]
test_mode = []
