#############################################
# FoundationDB Store configuration
#############################################

[store."foundationdb"]
type = "foundationdb"
#path = "/etc/foundationdb/fdb.cluster"

#[store."foundationdb".transaction]
#timeout = "5s"
#retry-limit = 10
#max-retry-delay = "1s"
#machine-id = "stalwart"
#data-center-id = "my-datacenter"

[store."foundationdb".purge]
frequency = "0 3 *"
