#############################################
# LMTP Directory configuration
#############################################

[directory."lmtp"]
type = "lmtp"
host = "127.0.0.1"
port = 11200
disable = true

[directory."lmtp".limits]
auth-errors = 3
rcpt = 5

[directory."lmtp".pool]
max-connections = 10

[directory."lmtp".pool.timeout]
create = "30s"
wait = "30s"
recycle = "30s"

[directory."lmtp".tls]
enable = false
allow-invalid-certs = true

[directory."lmtp".cache]
entries = 500
ttl = {positive = '1h', negative = '10m'}

[directory."lmtp".lookup]
domains = ["%{DEFAULT_DOMAIN}%"]

